// src/types/index.ts

export type Language = "en" | "zh";

export interface UserInput {
  topic: string;
  language: Language;
}

export interface Script {
  id: string; // Generated by backend
  style: string;
  hook: string;
  core_narrative: string;
  cta: string;
}

export interface InsightResponse {
  scripts: Script[];
  hashtags: string[];
  music_style: string;
  meta?: {
    request_id?: string;
    language?: Language;
    latency_ms?: number;
    model_used?: string;
  };
}

export interface ErrorResponse {
  code: 
    | "INVALID_INPUT" 
    | "NETWORK_ERROR" 
    | "PROVIDER_AUTH_ERROR" 
    | "PROVIDER_MODEL_NOT_FOUND" 
    | "RATE_LIMIT_EXCEEDED" 
    | "PROVIDER_ERROR" 
    | "INTERNAL_SERVER_ERROR";
  message: string;
  details?: string;
  retryable: boolean;
}